# SCRIPT TO GIVEN A LIST CALLED installed_packages
# RETURN THE RIGHT FORMAT TO INSTALL WITH PACKAGE CONTROL ADVANCED INSTALL

# INSTALL EXTENSION TYPESCRIPT FROM PACKAGECONTROL.IO

installed_packages = [
]

print(", ".join(installed_packages))